### PR TITLE
ENG Programme updates

### PR DESCRIPTION
**Pull request by nomadscientist**

### CODE REVIEW

**Comment by shiltemann** [comment]
wow nice! let me know how I can help here or when it is ready to merge! Glad you figured out the template a bit, hopefully we can make the process easier in the future

**Comment by nomadscientist** [comment]
Stuff I need help with:
 
Screenshot 2021-11-16 at 16 31 38 Can this become two large buttons that say 'CAT-Español' and 'HES-Español'? And then link somehow so we can track how often those particular buttons are used?
- Can the GTÑ logo be used in each bit
image (2)
?
- Finally, since these aren't really public yet, would it be possible to merge the changes now just so I can see them (the local hosting is not working for me... yet) and then can more easily keep working?

**Comment by nomadscientist** [comment]
Screenshot 2021-11-16 at 22 22 44
- [ ] "Instructors" shouldn't be here, right? How is that taken away?

**Comment by shiltemann** [comment]
ok, I will try to address the remaining point today :+1:

**Comment by nomadscientist** [comment]
Cool, so once you remove the 'get in touch every day if you want a certificate' bit from the general icebreaker, I think this is ready?

**Comment by nomadscientist** [comment]
Right, I think text-wise (I hope!) this is close enough we can go for the translation now.

**Pull request merged**
